# Location of top-level MicroPython directory
MPY_DIR = ../../../../Play32-micropython

# Name of module
MOD = ubmfont

# Source files (.c or .py)
SRC = ubmfont.py

# Architecture to build for (x86, x64, armv7m, xtensa, xtensawin)
ARCH = x64

# Include to get the rules for compiling and linking the module
include $(MPY_DIR)/py/dynruntime.mk
